{"name": "3. Клик по кнопке показать/скрыть пароль делает поле активным — подсвечивает его.", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=59607): Read timed out. (read timeout=120)", "trace": "self = <urllib3.connectionpool.HTTPConnectionPool object at 0x106958500>, conn = <urllib3.connection.HTTPConnection object at 0x106941430>, method = 'POST'\nurl = '/session/0aed69610acb78e94cfef4db698bc1d5/url', body = '{\"url\": \"https://stellarburgers.nomoreparties.site/reset-password\"}'\nheaders = HTTPHeaderDict({'Accept': 'application/json', 'Content-Type': 'application/json;charset=UTF-8', 'User-Agent': 'selenium/4.26.1 (python mac)', 'Connection': 'keep-alive'})\nretries = Retry(total=3, connect=None, read=None, redirect=None, status=None), timeout = Timeout(connect=120, read=120, total=None), chunked = False, response_conn = None\npreload_content = True, decode_content = True, enforce_content_length = True\n\n    def _make_request(\n        self,\n        conn: BaseHTTPConnection,\n        method: str,\n        url: str,\n        body: _TYPE_BODY | None = None,\n        headers: typing.Mapping[str, str] | None = None,\n        retries: Retry | None = None,\n        timeout: _TYPE_TIMEOUT = _DEFAULT_TIMEOUT,\n        chunked: bool = False,\n        response_conn: BaseHTTPConnection | None = None,\n        preload_content: bool = True,\n        decode_content: bool = True,\n        enforce_content_length: bool = True,\n    ) -> BaseHTTPResponse:\n        \"\"\"\n        Perform a request on a given urllib connection object taken from our\n        pool.\n    \n        :param conn:\n            a connection from one of our connection pools\n    \n        :param method:\n            HTTP request method (such as GET, POST, PUT, etc.)\n    \n        :param url:\n            The URL to perform the request on.\n    \n        :param body:\n            Data to send in the request body, either :class:`str`, :class:`bytes`,\n            an iterable of :class:`str`/:class:`bytes`, or a file-like object.\n    \n        :param headers:\n            Dictionary of custom headers to send, such as User-Agent,\n            If-None-Match, etc. If None, pool headers are used. If provided,\n            these headers completely replace any pool-specific headers.\n    \n        :param retries:\n            Configure the number of retries to allow before raising a\n            :class:`~urllib3.exceptions.MaxRetryError` exception.\n    \n            Pass ``None`` to retry until you receive a response. Pass a\n            :class:`~urllib3.util.retry.Retry` object for fine-grained control\n            over different types of retries.\n            Pass an integer number to retry connection errors that many times,\n            but no other types of errors. Pass zero to never retry.\n    \n            If ``False``, then retries are disabled and any exception is raised\n            immediately. Also, instead of raising a MaxRetryError on redirects,\n            the redirect response will be returned.\n    \n        :type retries: :class:`~urllib3.util.retry.Retry`, False, or an int.\n    \n        :param timeout:\n            If specified, overrides the default timeout for this one\n            request. It may be a float (in seconds) or an instance of\n            :class:`urllib3.util.Timeout`.\n    \n        :param chunked:\n            If True, urllib3 will send the body using chunked transfer\n            encoding. Otherwise, urllib3 will send the body using the standard\n            content-length form. Defaults to False.\n    \n        :param response_conn:\n            Set this to ``None`` if you will handle releasing the connection or\n            set the connection to have the response release it.\n    \n        :param preload_content:\n          If True, the response's body will be preloaded during construction.\n    \n        :param decode_content:\n            If True, will attempt to decode the body based on the\n            'content-encoding' header.\n    \n        :param enforce_content_length:\n            Enforce content length checking. Body returned by server must match\n            value of Content-Length header, if present. Otherwise, raise error.\n        \"\"\"\n        self.num_requests += 1\n    \n        timeout_obj = self._get_timeout(timeout)\n        timeout_obj.start_connect()\n        conn.timeout = Timeout.resolve_default_timeout(timeout_obj.connect_timeout)\n    \n        try:\n            # Trigger any extra validation we need to do.\n            try:\n                self._validate_conn(conn)\n            except (SocketTimeout, BaseSSLError) as e:\n                self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)\n                raise\n    \n        # _validate_conn() starts the connection to an HTTPS proxy\n        # so we need to wrap errors with 'ProxyError' here too.\n        except (\n            OSError,\n            NewConnectionError,\n            TimeoutError,\n            BaseSSLError,\n            CertificateError,\n            SSLError,\n        ) as e:\n            new_e: Exception = e\n            if isinstance(e, (BaseSSLError, CertificateError)):\n                new_e = SSLError(e)\n            # If the connection didn't successfully connect to it's proxy\n            # then there\n            if isinstance(\n                new_e, (OSError, NewConnectionError, TimeoutError, SSLError)\n            ) and (conn and conn.proxy and not conn.has_connected_to_proxy):\n                new_e = _wrap_proxy_error(new_e, conn.proxy.scheme)\n            raise new_e\n    \n        # conn.request() calls http.client.*.request, not the method in\n        # urllib3.request. It also calls makefile (recv) on the socket.\n        try:\n            conn.request(\n                method,\n                url,\n                body=body,\n                headers=headers,\n                chunked=chunked,\n                preload_content=preload_content,\n                decode_content=decode_content,\n                enforce_content_length=enforce_content_length,\n            )\n    \n        # We are swallowing BrokenPipeError (errno.EPIPE) since the server is\n        # legitimately able to close the connection after sending a valid response.\n        # With this behaviour, the received response is still readable.\n        except BrokenPipeError:\n            pass\n        except OSError as e:\n            # MacOS/Linux\n            # EPROTOTYPE and ECONNRESET are needed on macOS\n            # https://erickt.github.io/blog/2014/11/19/adventures-in-debugging-a-potential-osx-kernel-bug/\n            # Condition changed later to emit ECONNRESET instead of only EPROTOTYPE.\n            if e.errno != errno.EPROTOTYPE and e.errno != errno.ECONNRESET:\n                raise\n    \n        # Reset the timeout for the recv() on the socket\n        read_timeout = timeout_obj.read_timeout\n    \n        if not conn.is_closed:\n            # In Python 3 socket.py will catch EAGAIN and return None when you\n            # try and read into the file pointer created by http.client, which\n            # instead raises a BadStatusLine exception. Instead of catching\n            # the exception and assuming all BadStatusLine exceptions are read\n            # timeouts, check for a zero timeout before making the request.\n            if read_timeout == 0:\n                raise ReadTimeoutError(\n                    self, url, f\"Read timed out. (read timeout={read_timeout})\"\n                )\n            conn.timeout = read_timeout\n    \n        # Receive the response from the server\n        try:\n>           response = conn.getresponse()\n\n.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:536: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv/lib/python3.12/site-packages/urllib3/connection.py:507: in getresponse\n    httplib_response = super().getresponse()\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <socket.SocketIO object at 0x1069a2bc0>, b = <memory at 0x1069f8040>\n\n    def readinto(self, b):\n        \"\"\"Read up to len(b) bytes into the writable buffer *b* and return\n        the number of bytes read.  If the socket is non-blocking and no bytes\n        are available, None is returned.\n    \n        If *b* is non-empty, a 0 return value indicates that the connection\n        was shutdown at the other end.\n        \"\"\"\n        self._checkClosed()\n        self._checkReadable()\n        if self._timeout_occurred:\n            raise OSError(\"cannot read from timed out object\")\n        while True:\n            try:\n>               return self._sock.recv_into(b)\nE               TimeoutError: timed out\n\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py:720: TimeoutError\n\nThe above exception was the direct cause of the following exception:\n\nself = <tests.test_01_restore_password.TestRestorePassword object at 0x106958da0>, driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"0aed69610acb78e94cfef4db698bc1d5\")>\n\n    @allure.title(\"3. Клик по кнопке показать/скрыть пароль делает поле активным — подсвечивает его.\")\n    def test_toggle_password_field_activation(self, driver):\n        page = LoginPage(driver)\n>       page.open_restore_password_page()\n\ntests/test_01_restore_password.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage_objects/login_page.py:15: in open_restore_password_page\n    self.open_url(UrlsSiteData.RESET_PASSWORD_URL)\npage_objects/base_page.py:13: in open_url\n    self.driver.get(url)\n.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:389: in get\n    self.execute(Command.GET, {\"url\": url})\n.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:378: in execute\n    response = self.command_executor.execute(driver_command, params)\n.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py:391: in execute\n    return self._request(command_info[0], url, body=data)\n.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py:415: in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n.venv/lib/python3.12/site-packages/urllib3/_request_methods.py:143: in request\n    return self.request_encode_body(\n.venv/lib/python3.12/site-packages/urllib3/_request_methods.py:278: in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n.venv/lib/python3.12/site-packages/urllib3/poolmanager.py:443: in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:843: in urlopen\n    retries = retries.increment(\n.venv/lib/python3.12/site-packages/urllib3/util/retry.py:474: in increment\n    raise reraise(type(error), error, _stacktrace)\n.venv/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:789: in urlopen\n    response = self._make_request(\n.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <urllib3.connectionpool.HTTPConnectionPool object at 0x106958500>, err = TimeoutError('timed out'), url = '/session/0aed69610acb78e94cfef4db698bc1d5/url', timeout_value = 120\n\n    def _raise_timeout(\n        self,\n        err: BaseSSLError | OSError | SocketTimeout,\n        url: str,\n        timeout_value: _TYPE_TIMEOUT | None,\n    ) -> None:\n        \"\"\"Is the error actually a timeout? Will raise a ReadTimeout or pass\"\"\"\n    \n        if isinstance(err, SocketTimeout):\n>           raise ReadTimeoutError(\n                self, url, f\"Read timed out. (read timeout={timeout_value})\"\n            ) from err\nE           urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=59607): Read timed out. (read timeout=120)\n\n.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:369: ReadTimeoutError"}, "steps": [{"name": "Открыть страницу: 'https://stellarburgers.nomoreparties.site/reset-password'", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=59607): Read timed out. (read timeout=120)\n", "trace": "  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/page_objects/base_page.py\", line 13, in open_url\n    self.driver.get(url)\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 389, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 391, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 415, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/urllib3/util/retry.py\", line 474, in increment\n    raise reraise(type(error), error, _stacktrace)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/urllib3/util/util.py\", line 39, in reraise\n    raise value\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 789, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"/Users/vladvihrov/PycharmProjects/Diplom_3/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 369, in _raise_timeout\n    raise ReadTimeoutError(\n"}, "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/reset-password'"}], "start": 1731265786839, "stop": 1731265906843}], "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1731265786839, "stop": 1731265906857, "uuid": "09f33f37-e350-463b-9150-8e93fcbd1098", "historyId": "a8b471f1e133286ca5e0200d9927739e", "testCaseId": "37f47d25159fa0932dc3722d45b4dc3c", "fullName": "tests.test_01_restore_password.TestRestorePassword#test_toggle_password_field_activation", "labels": [{"name": "story", "value": "1. Восстановление пароля"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_01_restore_password"}, {"name": "subSuite", "value": "TestRestorePassword"}, {"name": "host", "value": "MBP-Vlad"}, {"name": "thread", "value": "17651-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_01_restore_password"}]}